"""empty message

Revision ID: 61050faa8cf2
Revises: 87371a14f01b
Create Date: 2022-11-17 00:43:54.111593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61050faa8cf2'
down_revision = '87371a14f01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
